name: C++ code linter
description: Automatically checks pull requests changes with cpplint and posts the comment with result.
author: JSUYA (jsuya.choi@samsung.com)
branding:
  icon: alert-circle
  color: green
runs:
  using: 'docker'
  image: 'Dockerfile'
